name: "Build and push images"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-push:
    if: github.server_url == 'https://github.com' && github.repository == 'sebatec-eu/forgejo-runner-images'
    strategy:
      fail-fast: false
      matrix:
        runners:
          - release: stable
            tags:
              - "latest"
              - "1"
              - "1.0"
              - "1.0.0"
          - release: testing
            tags:
              - "latest"
              - "1"
              - "1.0"
              - "1.0.0"
    concurrency:
      group: ${{ github.workflow }}-${{ toJSON(matrix.runners) }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    container:
      image: "docker.io/debian:testing"
      options: --privileged
    permissions:
      packages: write
    steps:
      - name: Install relevant tools
        run: apt-get update && apt-get install -y podman mkosi make
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Checkout (GitHub)
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Build container
        run: make build-${{ matrix.runners.release }}
      - name: Login to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          auth_file_path: /tmp/auth.json
      - name: Push container
        run: make push-${{ matrix.runners.release }}
        env:
          TAGS: ${{ join(matrix.runners.tags, ' ') }}
          REGISTRY_AUTH_FILE: /tmp/auth.json
